houseDjango/house/urls.py
from django.urls import re_path
from . import views

urlpatterns = [
    re_path(r'^$', views.showHouses, name='houses'),
    re_path(r'^newHouse$', views.addHouse, name='newHouse'),
    re_path(r'^editHouse/(?P<houseID>\d+)/$', views.editHouse, name='editHouse'),
    re_path(r'^deleteHouse/(?P<houseID>\d+)/$', views.deleteHouse, name='deleteHouse'),
    re_path(r'^queryHouse/$', views.queryHouseInfo, name='queryHouse')
]

houseDjango/houseDjango/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.views import static ##新增
from django.conf.urls.static import static as staticDef
from django.conf import settings ##新增
from django.conf.urls import url ##新增


urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^', include(('house.urls'))),
    re_path(r'^user/', include(('users.urls', 'user'), namespace='user')),
    re_path(r'^house/', include(('house.urls', 'houses'), namespace='houses')),
    re_path(r'^logging/', include(('loggings.urls', 'logging'), namespace='logging')),
    re_path(r'^lease/', include(('lease.urls', 'leases'), namespace='leases')),
    re_path(r'^print/', include(('print.urls', 'print'), namespace='print')),
    re_path(r'^realty/', include(('realty.urls', 'realtys'), namespace='realtys')),
    url(r'^static/(?P<path>.*)$', static.serve, {'document_root': settings.STATIC_ROOT}, name='static')
] + staticDef(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

houseDjango/lease/urls.py
from django.urls import re_path
from . import views

urlpatterns = [
    re_path(r'^$', views.showLeases, name='leases'),
    re_path(r'^newLease$', views.addLease, name='newLease'),
    re_path(r'^editLease/(?P<leaseID>\d+)/$', views.editLease, name='editLease'),
    re_path(r'^deleteLease/(?P<leaseID>\d+)/$', views.deleteLease, name='deleteLease'),
    re_path(r'queryLeases/', views.queryLeaseInfos, name='queryLeases'),
    re_path(r'queryHouse/', views.queryHouseInfo, name='queryHouse'),
    re_path(r'shenPiLease', views.shenPiLease, name='shenPiLease')
]

houseDjango/realty/urls.py
from django.urls import re_path
from . import views

urlpatterns = [
    re_path(r'^$', views.showRealtyInfos, name='realtys'),
    re_path(r'^newRealty$', views.addRealtyInfo, name='newRealty'),
    re_path(r'^editRealty/(?P<realtyID>\d+)/$', views.exitRealtyInfo, name='editRealty'),
    re_path(r'^deleteRealty/(?P<realtyID>\d+)/$', views.deleteRealtyInfo, name='deleteRealty')
]

houseDjango/users/urls.py
from django.urls import re_path
from . import views

urlpatterns = [
    re_path(r'^login/$', views.userLogin, name='login'),
    re_path(r'^logout/$', views.userLogout, name='logout'),
    re_path(r'^$', views.shouUserInfo, name='user'),
    re_path(r'^searchUser/$', views.searchUser, name='searchUser'),
    re_path(r'^newUser/$', views.addUser, name='newUser'),
    re_path(r'^editUser/(?P<userID>\d+)/$', views.editUser, name='editUser'),
    re_path(r'^deleteUser/(?P<userID>\d+)/$', views.deleteUser, name='deleteUser'),
]

houseDjango/users/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser


# Create your models here.
class userProfile(AbstractUser):
    displayName = models.CharField('显示名称', max_length=150, blank=True)

    authority = models.CharField('用户权限', max_length=50, blank=True)

    telephone = models.CharField('联系电话', max_length=15, blank=True)

    class Meta:
        verbose_name = '用户信息'
        verbose_name_plural = '用户信息'

    def __str__(self):
        return super().__str__()

houseDjango/users/forms.py
from django import forms
from .models import userProfile


class userProfileForm(forms.ModelForm):
    class Meta:
        model = userProfile
        fields = ['username', 'displayName', 'telephone', 'authority']

houseDjango/users/views.py
from django.contrib.auth import authenticate, logout, login
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, reverse
from django.core import serializers

from tools.query import getDict

from .models import userProfile
from .forms import userProfileForm

import json
# Create your views here.


def userLogin(request):
    if request.method != "POST":
        return render(request, 'users/login.html')
    else:
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user and user.is_active:
            login(request, user)
            return HttpResponseRedirect(reverse('houses:houses'))
            # return render(request, reverse('houses:houses'), context)
        else:
            return HttpResponseRedirect(reverse('user:login'))

@login_required
def userLogout(request):
    logout(request)
    return HttpResponseRedirect(reverse('user:login'))

@login_required
def shouUserInfo(request):
    users = getUserInfo()
    dic = getDict()
    context = {'userInfos': users, 'dicts': dic}
    return render(request, 'users/index.html', context)


@login_required
def addUser(request):
    if request.method != "POST":
        form = userProfileForm()
    else:
        form = userProfileForm(request.POST)
        if form.is_valid():
            disName = form.cleaned_data['displayName']
            if disName == '':
                usrName = form.cleaned_data['username']
                currentForm = form.save(commit=False)
                currentForm.displayName = usrName
                currentForm.save()
            else:
                form.save()
                context = {'status': 200}
                return HttpResponse(json.dumps(context))
            return HttpResponseRedirect(reverse('user:user'))

    context = {'form': form}
    return render(request, 'house/index.html', context)


@login_required
def editUser(request, userID):
    # 编辑房屋信息
    tempUser = userProfile.objects.get(id=userID)
    if request.method != "POST":
        form = userProfileForm(instance=tempUser)
    else:
        form = userProfileForm(instance=tempUser, data=request.POST)
        if form.is_valid():
            currentPassword = request.POST.get('password')
            if not currentPassword == '':
                tempUser.set_password(currentPassword)

            disName = form.cleaned_data['displayName']
            if disName == '':
                usrName = form.cleaned_data['username']
                currentForm = form.save(commit=False)
                currentForm.displayName = usrName
                currentForm.save()
            else:
                form.save()
                context = {'status': 200}
                return HttpResponse(json.dumps(context))
            return HttpResponseRedirect(reverse('user:user'))
    return render(request, 'users/index.html', {'form': form})



@login_required
def deleteUser(request, userID):
    # 编辑房屋信息
    tempUser = userProfile.objects.get(id=userID)
    if tempUser:
        tempUser.delete()
        return HttpResponseRedirect(reverse('user:user'))
    else:
        pass


def searchUser(request):
    return HttpResponseRedirect(reverse("user:showUserInfo"))


def getUserInfo():
    # 获取房屋信息
    user = userProfile.objects.filter()

    data = serializers.serialize('json', user)
    return data

houseDjango/users/templates/users/base.html
<!doctype html>
{% load bootstrap3 %}
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>租凭管理系统</title>
{% bootstrap_css %}
{% bootstrap_javascript %}
{% load userTool %}
<!--<script type="text/javascript" src="/static/js/baseInit.js"></script>-->
<!--<script type="text/javascript">
	window.onload = function (){
		// baseInit();
	}
</script>-->
</head>
<body>
	<!-- Static navbar -->
<!--	<input id="dictsData" type="hidden" data="{{ dicts }}" />-->
<!--	<input id="userData" type="hidden" data="{{ user }}" />-->
	<nav class="navbar navbar-default navbar-static-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed"
				data-toggle="collapse" data-target="#navbar"
				aria-expanded="false" aria-controls="navbar">
				</button>
<!--				<a class="navbar-brand" href="{% url 'leases:leases' %}">房屋租凭管理系统</a>-->
				<a class="navbar-brand">房屋租凭管理系统</a>
			</div>
			<div id="navbar" class="navbar-collapse collapse">
				{% if user.is_authenticated %}
				<ul class="nav navbar-nav">
					{% if user.authority|authorityIndexOf:'房屋' %}
					<li id="houseHref"><a href="{% url 'houses:houses' %}">房屋信息管理</a></li>
					{% endif %}
					{% if user.authority|authorityIndexOf:'租凭' %}
					<li id="leaseHref"><a href="{% url 'leases:leases' %}">租凭信息管理</a></li>
					{% endif %}
					{% if user.authority|authorityIndexOf:'经纪' %}
					<li id="realtyHref"><a href="{% url 'realtys:realtys' %}">经纪信息管理</a></li>
					{% endif %}
					{% if user.authority|authorityIndexOf:'用户' %}
					<li id="userHref"><a href="{% url 'user:user' %}">用户信息管理</a></li>
					{% endif %}
				</ul>
				{% endif %}
				<ul class="nav navbar-nav navbar-right">
					{% if user.is_authenticated %}
					<li><a>您好, {{ user.displayName }}.</a></li>
					<li><a class="btn btn-outline-primary" href="{% url 'user:logout' %}">注销</a></li>
					{% else %}
					<li><a class="btn btn-outline-primary" href="{% url 'user:login' %}">登录</a></li>
					{% endif %}
				</ul>
			</div><!--/.nav-collapse -->
		</div>
	</nav>
	<!--<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
		<a class="navbar-brand" href="{% url 'houses:houses' %}">房屋租凭管理系统</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarCollapse">
			<ul class="navbar-nav mr-auto">
			  <li class="nav-item active">
				<a class="nav-link" href="{% url 'houses:houses' %}">房屋信息管理系统 <span class="sr-only">(current)</span></a>
			  </li>
			  <li class="nav-item">
				<a class="nav-link" href="{% url 'leases:leases' %}">租凭信息管理系统</a>
			  </li>
			</ul>
			<form class="form-inline mt-2 mt-md-0">
				<ul class="nav navbar-nav navbar-right">
					{% if user.is_authenticated %}
					<li><a>您好, {{ user.username }}.</a></li>
					<li><a href="">注销</a></li>
					{% else %}
					<li><a href="">登录</a></li>
					{% endif %}
				</ul>
			</form>
		</div>
	</nav>-->
	<main role="main" class="container">
		{% block content %} {% endblock content %}
	</main>
</body>
</html>

houseDjango/users/templates/users/index.html
<!doctype html>
<html>
<head>
	<meta charset="utf-8">
	<title>用户信息</title>
	<script type="text/javascript" src="../static/js/jquery.min.js"></script>
	<!--<script type="text/javascript" src="http://cdn.static.runoob.com/libs/jquery/1.10.2/jquery.min.js"></script>-->
	<script type="text/javascript" src="../static/js/init.js"></script>
	<script type="text/javascript" src="../static/js/TableBase.js"></script>
	<script type="text/javascript" src="../static/js/InformationBase.js"></script>
	<script type="text/javascript" src="../static/js/DragDiv.js"></script>
	<script type="text/javascript" src="../static/js/PrintFile.js"></script>
	<script type="text/javascript">
		var modelName = 'user';
		var dics;
		var infoData;
		var currentInfo;
		window.onload = function(){
			init();
		}
	</script>
	<link href="../static/css/drag.css" rel="stylesheet" media="screen"/>
	<link href="../static/css/user.css" rel="stylesheet" media="screen"/>
	<link href="../static/css/TableBase.css" rel="stylesheet" media="screen"/>
</head>

<body>
	{% extends 'users/base.html' %}
	{% load bootstrap3 %}
	{% load userTool %}
	{% block content %}
	<input id="dictsData" type="hidden" data="{{ dicts }}" />
	<input id="infoData" type="hidden" data="{{ userInfos }}" />
	<div class="table-responsive">
		<div>
			{% if user.authority|userAuthority:'增删改' %}
			<input id="addUserBtn" class="btn btn-primary btn-lg" type="button" onClick="openUserPopup(this);" value="添加用户信息"/>
			<input id="editUserBtn" class="btn btn-primary btn-lg" type="button" disabled="disabled" onClick="openUserPopup(this);" value="修改"/>
			{% endif %}
			{% if user.authority|userAuthority:'查看' %}
			<input id="viewUserBtn" class="btn btn-primary btn-lg" type="button" disabled="disabled" onClick="openUserPopup(this);" value="查看"/>
			{% endif %}
			{% if user.authority|userAuthority:'增删改' %}
			<input id="delUserBtn" class="btn btn-primary btn-lg" type="button" disabled="disabled" onClick="deleteUserInfo()" value="删除"/>
			{% endif %}
		</div>
		<table id="userInformationTalbe" class="table table-striped table-sm">
			<thead class="infoTableHead">
				<tr>
					<th data="username">登录名</th>
					<!--<th data="password">密码</th>-->
					<th data="displayName">用户名</th>
					<th data="telephone">联系电话</th>
					<th data="authority" dictType="userAuthority">权限</th>
				</tr>
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>

	<div id="popupMake" class="Dialog-make" style="display: none; z-index: 98;"></div>
	<div id="userAddDiv" class="addEditPopupDiv" style="width: 650px; height: 520px; z-index: 99;">
		<div id="userAddTop" class="popupTopDiv" onMouseDown="divDragStart(event);" onMouseUp="divDragEnd(event);">
			<label style="user-select: none; width: 200px; float: left; pointer-events: none;">用户信息</label>
			<span style="width: 100%; pointer-events: none;"></span>
			<a onClick="closeUserPopup();" style="float: right; cursor: pointer; padding-right: 5px;">X</a>
		</div>
		<div class="popupBodyDiv">
			<form id="userForm" class="needs-validation" style="width: inherit; overflow-x: hidden; overflow-y: auto; margin-bottom: 70px;">
				{% csrf_token %}
				<div class="row" style="height: 70px">
					<div class="col-md-6 mb-3">
						<label for="username">登录名</label>
						<input id="username" class="form-control" type="text" name="username"/>
						<div class="invalid-feedback"></div>
					</div>
					<div class="col-md-6 mb-3">
						<label for="password">密码</label>
						<input id="password" class="form-control" type="text" name="password"/>
						<div class="invalid-feedback"></div>
					</div>
				</div>
				<div class="row" style="height: 70px">
					<div class="col-md-6 mb-3">
						<label for="displayName">用户名</label>
						<input id="displayName" class="form-control" type="text" name="displayName"/>
						<div class="invalid-feedback"></div>
					</div>
					<div class="col-md-6 mb-3">
						<label for="telephone">联系电话</label>
						<input id="telephone" class="form-control" type="text" name="telephone"/>
						<div class="invalid-feedback"></div>
					</div>
				</div>
				<div class="row">
					<div class="col-md-6">
						<label>用户权限:</label>
						<div class="" style="display: flex; width: 100%;">
							<div class="user_authority" style="width: 300px;">
								<label>可用 用户权限</label>
								<p id="id_user_permissions_filter" class="selector-filter">
									<input type="text" placeholder="过滤" id="id_user_permissions_input" onmousedown="filterUserAuthority();">
								</p>
								<select name="user_permissions_list" id="user_authority_list"
										multiple="" class="filtered" style="width: 270px; height: 170px;">
								</select>
								<!--<a title="点击选择全部用户权限。" href="#" id="id_user_permissions_add_all_link"
								   class="selector-chooseall active">全选</a>-->
							</div>
							<div class="user_authority" style="list-style: none; width: 100px;">
								<a title="选择" id="id_user_permissions_add_link"
									   class="selector-add active" onclick="userAuthorityAdd();">选择》</a>
								<a title="删除" id="id_user_permissions_remove_link"
									   class="selector-remove" onclick="userAuthorityDel();">《删除</a>
							</div>
							<div class="user_authority">
								<label>选中的 用户权限</label>
								<select id="user_authority" multiple="" size="0"
										name="user_permissions" class="filtered" style="width: 270px; height: 210px;">
								</select>
								<!--<a title="删除所有已选择的用户权限。" href=""
								   id="id_user_permissions_remove_all_link"
								   class="selector-clearall">删除全部</a>-->
							</div>
						</div>
					</div>
				</div>
			</form>
			<div id="formBtnDiv" class="btnDiv row">
				<input type="submit" class="btn btn-primary btn-lg" value="保存" onclick="submitUser();"/>
				<input type="button" class="btn btn-primary btn-lg" onClick="closeUserPopup();" value="取消"/>
			</div>
		</div>
	</div>
	{% endblock content %}
</body>
</html>

houseDjango/users/templates/users/login.html
<!doctype html>
<html>
<head>
	<meta charset="utf-8">
	<title>租凭管理系统-登录</title>
	<link href="signin.css" rel="stylesheet">
</head>

<body class="text-center">
	{% extends 'users/base.html' %}
	{% block content %}
	<div id="login_frame" style="top: 50%; left: 50%; position:absolute; width: 400px;transform:translateX(-50%) translateY(-50%);">
		{% if form.error %}
			<p>用户名密码错误</p>
		{% endif %}
		<form class="form-signin" action="{% url 'user:login' %}"  method="post">
			{% csrf_token %}
			<h1 class="h3 mb-3 font-weight-normal">请登录</h1>
			<label for="inputEmail" class="sr-only">用户名</label>
			<input type="text" id="inputEmail" name="username" class="form-control" placeholder="用户名" required autofocus>
			<label for="inputPassword" class="sr-only">用户密码</label>
			<input type="password" id="inputPassword" name="password" class="form-control" placeholder="用户密码" required>
			<div class="checkbox mb-3">
				<label>
				  <input type="checkbox" value="remember-me"> 记住我
				</label>
			</div>
			<button class="btn btn-lg btn-primary btn-block" type="submit">登录</button>
		</form>
	</div>
	{% endblock content %}
</body>
</html>